package com.escrow.deal_service.domain;

public enum DealState {
  DRAFT,
  AWAITING_AGREEMENT,
  AGREED,
  ACCOUNT_OPENED,
  AWAITING_FUNDING,
  FUNDING_PROCESSING,
  FUNDS_SECURED,
  AWAITING_BENEFICIARY_FULFILLMENT,
  AWAITING_DEPOSITOR_REVIEW,
  RELEASE_PENDING,
  RELEASED,
  REFUND_PENDING,
  REFUNDED,
  DISPUTED,
  CLOSED
}
